//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlogSitem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumId { get; set; }
        public string Yorum1 { get; set; }
        public int MakaleID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public string AdSoyad { get; set; }
        public int Begeni { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
